#######################################
# 说明:
# 1. 井号(#)为注释
# 2. 缩进严格对齐，使用空格缩进, 注意有些冒号后面有一个空格, 有些没有空格
# 3. 请使用英文字符
# 4. 更多yaml语法请上网查看
#######################################


# 作品(视频或图集)、直播、合集、音乐集合、个人主页的分享链接或者电脑浏览器网址
# (删除文案, 保证只有URL, https://v.douyin.com/kcvMpuN/ 或者 https://www.douyin.com/开头的)
# 可以设置多个链接, 确保至少一个链接
# 必选
link:
  # 单个作品链接示例
  # - https://v.douyin.com/kVefc81/
  # - https://v.douyin.com/kVdkdxY/
  # - https://v.douyin.com/kVdMcrr/
  # - https://v.douyin.com/iRGu2mBL/
  # - https://v.douyin.com/iRGukBBk/
  # - https://v.douyin.com/iRGuJcW8/
  # - https://v.douyin.com/iRGHQY5t/

  # 用户主页链接示例
#  - https://www.douyin.com/user/MS4wLjABAAAAFrlzDwUqEjnxAzQfHTIAKiVUe76MymbzDq74ptEz9MtuZZEsneR4x5POh_nFyYN-?from_tab_name=main
#  - https://www.douyin.com/user/MS4wLjABAAAAqnq-IVJZI4G4qpTDZFyUFIGuEvxz53P-XOUl0gX96sI?from_tab_name=main&vid=7513470216417037627
#  - https://www.douyin.com/user/MS4wLjABAAAA0aVkqV_T5cJ9SnNlOv9K5J921TtoIQ5JLVYsHzPGbAM?enter_from=live_detail&from_tab_name=main
#  - https://www.douyin.com/user/MS4wLjABAAAA8HZMhOtYrVWIrJpatn8qDerHqJwU9lq0auwzKB_WGu0?from_tab_name=main&is_search=1&list_name=follow&nt=0
#  - https://www.douyin.com/user/MS4wLjABAAAA0KmDbFkgdpSPBwnlqH--Dt7GKDVRz0daTc8gZjrfg-0HegUos0tFZbbnbQXJ9Ibc?from_tab_name=main&is_search=1&list_name=follow&nt=0
#  - https://www.douyin.com/user/MS4wLjABAAAAc7yP0MwxHEAZs-eIfu14qv6nKvYMqiAfPgp7pk6SoQmnOiEQyuzKD2xN7uwnSO_0?from_tab_name=main&is_search=1&list_name=follow&nt=0
#  - https://www.douyin.com/user/MS4wLjABAAAAcKSmQ71gWsqyPSph8f5ul2Q9SZJOjx4IPbaBqv-uUEQ?from_tab_name=main
#  - https://www.douyin.com/user/MS4wLjABAAAAitXV3RYhdgtY6JenK5k2c9iJPBCQZ6b-2JjTmaiNenA?from_tab_name=main
#  - https://www.douyin.com/user/MS4wLjABAAAAkb3B2clsVyCXIUanY_R9XkZte57FuKQVr6UUAVPiSvY?from_tab_name=main
#  - https://www.douyin.com/user/MS4wLjABAAAAAQd3ZM6hhAUPZRIJyQGjuG4pE-HDZOOyjnn686HHXdA?from_tab_name=main&vid=7526182445143821626
#  - https://www.douyin.com/user/MS4wLjABAAAAWr_9y0rRXCpJzOU9BUUvt2wIu4_rdkoKpkm1klELPm0?from_tab_name=main&is_search=0&list_name=follow&nt=6
#  - https://www.douyin.com/user/MS4wLjABAAAAlj8mMxFBeiiE1r_dattQ6Rpr9HCN3wxBJxZyBulyXj-hHAyGiTLj-98H7wuUbRr4?from_tab_name=main&is_search=0&list_name=follow&nt=4
#  - https://www.douyin.com/user/MS4wLjABAAAApV-C05BNjW7ApBX-pIFkrryF8g7OzRjSv5l8ZgPVqis?from_tab_name=main&is_search=0&list_name=follow&nt=1
#  - https://www.douyin.com/user/MS4wLjABAAAAzV2hNXsR8bpJiiKJXHVaM-VtedgJj6qBFo-aZ4ixKkw?from_tab_name=main&is_search=0&list_name=follow&nt=2
#  - https://www.douyin.com/user/MS4wLjABAAAANks95vm-QdtrlR1xpCx4X9FZjC6DUUBvuez2QwRuGljKlij8InlytiSkwo-jsQoj?from_tab_name=main&is_search=0&list_name=follow&nt=6
#  - https://www.douyin.com/user/MS4wLjABAAAAsPPhVJlVuEDICoCZfqPP5AJa4r3atOcJtguySwlZNTUgyoDejkM_sQ6bUTjLVhhk?from_tab_name=main&is_search=0&list_name=follow&nt=1
#  - https://www.douyin.com/user/MS4wLjABAAAAfNY2IHUnjb3LbBCBxmHr7qtd5B84koxhue0TlnltPIQ?from_tab_name=main&is_search=0&list_name=follow&nt=6
#  - https://www.douyin.com/user/MS4wLjABAAAAdFc69YowYQxY2YlTWU0riFYRkyWRWzMqwkksjVknNhZcs11dsPxilGKVFDEEY7k3?from_tab_name=main&is_search=0&list_name=follow&nt=6
#  - https://www.douyin.com/user/MS4wLjABAAAArLE7NSbcXaE7009NE69EHNhVR7JSrcP5LUljy95y0Ho?from_tab_name=main&is_search=0&list_name=follow&nt=4
#  - https://www.douyin.com/user/MS4wLjABAAAAl7BTXColKGaNMfIole51EG7kznqmEEl0oXVZxiyrH28?from_tab_name=main&is_search=0&list_name=follow&nt=2
#  - https://www.douyin.com/user/MS4wLjABAAAAeCM_FQkpLUMDrOOs1Bhvi-e1LuULutp03Oht0HrkwPFIMIhv-a7MYqkBOD-aCwkV?from_tab_name=main&is_search=0&list_name=follow&nt=2
#  - https://www.douyin.com/user/MS4wLjABAAAAclgaWyBukn9kxecJw_njDQc2PtmPgZ61SheLMNvDfQw?from_tab_name=main&is_search=0&list_name=follow&nt=8
#  - https://www.douyin.com/user/MS4wLjABAAAAU0gZCjdjcvr2ZKUM5RlV1XnUXrVj7hMg9z7e9CVSMS0?from_tab_name=main&is_search=0&list_name=follow&nt=4
#  - https://www.douyin.com/user/MS4wLjABAAAABJwNZuR5ysUIcqYrhiuygzZKpj4qKN7p86Qv_qhg2Jjlg4zARb51gpZvFJD8jDOL?from_tab_name=main&is_search=0&list_name=follow&nt=7
#  - https://www.douyin.com/user/MS4wLjABAAAAIzXYX3-YrgXsbEZMLDALKX4369RgY8BpVBo7kvyHQzI?from_tab_name=main&is_search=0&list_name=follow&nt=6
#  - https://www.douyin.com/user/MS4wLjABAAAAwLXT6Dd8Xorw2DlbIt7GbTzjxW0g1RU32oELlf65iD0?from_tab_name=main&is_search=0&list_name=follow&nt=1
#  - https://www.douyin.com/user/MS4wLjABAAAAgOeOms9eDZosgQd4dUMrxsD53sNhj7q3LA-nqqU0KQs6YUD0H5_OVJmzE6YIVXDK?from_tab_name=main&is_search=0&list_name=follow&nt=2
#  - https://www.douyin.com/user/MS4wLjABAAAA4EaMQ9ujsTGU0c60bemjtvjfEqtLhF4M-KVS0E0Npq0?from_tab_name=main&is_search=0&list_name=follow&nt=1
#  - https://www.douyin.com/user/MS4wLjABAAAAqUTmqgsjIsohymrVYMOCoEVTNWoIozVlFcOzrQ_0LFOa2dvILzXxIYNXifuPvoz3?from_tab_name=main&is_search=0&list_name=follow&nt=1
#  - https://www.douyin.com/user/MS4wLjABAAAAQo3yi3HUwNDAnuAnHXVRZPZyxgZIyOUXrahE8o4X_RJkjOky0RmWzHuiKrdrELoA?from_tab_name=main&is_search=0&list_name=follow&nt=1
#  - https://www.douyin.com/user/MS4wLjABAAAAhhzv3i9X0hiae4j4OlpOGydaezI2nOZDcmJY59ClHBU?from_tab_name=main&is_search=0&list_name=follow&nt=4
#  - https://www.douyin.com/user/MS4wLjABAAAAk2I7kDY3SICqHHWzOuZui-nwGOJJNGaYQ5YbJKM36NE?from_tab_name=main&is_search=0&list_name=follow&nt=2
#  - https://www.douyin.com/user/MS4wLjABAAAAApiZzS78lY4nJFr8MBLBp6pLI_kB2i8tcM2L5PBZgW0?from_tab_name=main&is_search=0&list_name=follow&nt=2
#  - https://www.douyin.com/user/MS4wLjABAAAADuTJkeJeDbKDjdbwNeB8bP81pVX_MWRnncAbPyu2DiE?from_tab_name=main&is_search=0&list_name=follow&nt=0
#  - https://www.douyin.com/user/MS4wLjABAAAA4eO4czYKNAlV7v9f9M63_0_wkvwL3jR0HBFPvMOBs8E?from_tab_name=main&is_search=0&list_name=follow&nt=10
#  - https://www.douyin.com/user/MS4wLjABAAAAEftCJbdTfYPATSy6uy4DpMYpDHvRrgPkX50_03oxJPs?from_tab_name=main&is_search=0&list_name=follow&nt=0
#  - https://www.douyin.com/user/MS4wLjABAAAAqKToxd76zqkgxoamN9_w55wxrOxZWsvp5n6JMTz5wps?from_tab_name=main&is_search=0&list_name=follow&nt=3
#  - https://www.douyin.com/user/MS4wLjABAAAAx2wCqE5K6HjsRWqekZwYk89-s6qdFVnodkJ4u1DP6i0?from_tab_name=main&is_search=0&list_name=follow&nt=2
  - https://www.douyin.com/user/MS4wLjABAAAA5-xUx_sj2U1rozIoGV1LbMfEFzYrSgAR61LteJnhSko?from_tab_name=main&is_search=0&list_name=follow&nt=3
  - https://www.douyin.com/user/MS4wLjABAAAAUaWh-L1KcV4pvErcbC3wYttiwGSsu9AHGoB7eNnwELQ?from_tab_name=main&is_search=0&list_name=follow&nt=11
  - https://www.douyin.com/user/MS4wLjABAAAAnD83KZjeQTUzwYBrTZSML3bRiabZjTiJUh80s3FS_sM?from_tab_name=main&is_search=0&list_name=follow&nt=0
  - https://www.douyin.com/user/MS4wLjABAAAABAMy6-dsUuxfMAWAZDSgwgodEW-auRXAjMqlZ2XIjp8?from_tab_name=main&is_search=0&list_name=follow&nt=1
  - https://www.douyin.com/user/MS4wLjABAAAApZWsFLuNZ-qEbXOZy--lfLKcp91dzaDQ3A6ulY3dSVc?from_tab_name=main&is_search=0&list_name=follow&nt=0
  - https://www.douyin.com/user/MS4wLjABAAAAYpRkrtWWSV1S66uje2ey40xB7TdHPTS_hZxZl4Tr9dI?from_tab_name=main&is_search=0&list_name=follow&nt=0
  - https://www.douyin.com/user/MS4wLjABAAAAZTB5NgQ6l2RZKin2OGBAPPVAfMwwhnWwc_zoioUeS5g?from_tab_name=main&is_search=0&list_name=follow&nt=1
  - https://www.douyin.com/user/MS4wLjABAAAAMn__d0rqdcuqb1lVJKapsl-ssFNQnayKwd136gpbScI?from_tab_name=main&is_search=0&list_name=follow&nt=4
  - https://www.douyin.com/user/MS4wLjABAAAA1Fj097NCq6bxlAwdut0iieJE0BPWIhKftqVU_f8ijwc?from_tab_name=main&is_search=0&list_name=follow&nt=1
  - https://www.douyin.com/user/MS4wLjABAAAAkW9ijrcruGIyc2N0upur921QGujQggC2YjVhaPLcp3Y?from_tab_name=main&is_search=0&list_name=follow&nt=2
  - https://www.douyin.com/user/MS4wLjABAAAADgP0Ym8exwIZxEPvvlR7oLg-H9NUwGmjohhvYY1rBfs?from_tab_name=main&is_search=0&list_name=follow&nt=4
  - https://www.douyin.com/user/MS4wLjABAAAABpCLp15j1TP0m8DHdq1PIdQfdhKH2ste2cUKaAvOJRPCKM-TAtMgbfL0tWUOVChF?from_tab_name=main&is_search=0&list_name=follow&nt=4
  - https://www.douyin.com/user/MS4wLjABAAAAF5Bix2bX1Qf0yimtUYQEMDvShGvduayY7GZdih5CrqN17Bz94-FBTiD3q0kAaumK?from_tab_name=main&is_search=0&list_name=follow&nt=4
  - https://www.douyin.com/user/MS4wLjABAAAA45g_2JMODwoBnYcPMsBBUx64kxlhO1A1Mhr4JLCEozQ?from_tab_name=main&is_search=0&list_name=follow&nt=7
  - https://www.douyin.com/user/MS4wLjABAAAAjMxX680UkwsISNXiAWCgSEymKPssDTb5yu3X_7Bu-Ak?from_tab_name=main&is_search=0&list_name=follow&nt=2
  - https://www.douyin.com/user/MS4wLjABAAAAfAME7Hj42AP78o-4zGBt0FKonnBVYEqqSppLavMrzlGAUHe_imSkebqtBB6UDO1F?from_tab_name=main&is_search=0&list_name=follow&nt=2
  - https://www.douyin.com/user/MS4wLjABAAAAsjmv6Ri0jCNvzT5Fy7ksCRJLiHuA5faDmrLersXCag0?from_tab_name=main&is_search=0&list_name=follow&nt=0
  - https://www.douyin.com/user/MS4wLjABAAAAWWTgmTtHELDq3SM5ztCMmor3d1MxS9qpJReprhjKQGM?from_tab_name=main&is_search=0&list_name=follow&nt=3
  - https://www.douyin.com/user/MS4wLjABAAAA6Fn_5DwRGDfRBGfjcC-3YAfL6XkOm0JMi_oinPje-TA?from_tab_name=main&is_search=0&list_name=follow&nt=4
  - https://www.douyin.com/user/MS4wLjABAAAADw1dDJd4zddv0m8KWQB7ztFV0Nt8QzIK7dpFvbsrXss?from_tab_name=main&is_search=0&list_name=follow&nt=4
  - https://www.douyin.com/user/MS4wLjABAAAACBL_bft6pc81qoJGabutmg0oMx0QRfZrIZsT2CWfH7Y?from_tab_name=main&is_search=0&list_name=follow&nt=4
  - https://www.douyin.com/user/MS4wLjABAAAAVrCkTiidCghE95ZTugMnFgqxdQ6Ut5yo4DBVs7D-zZ0?from_tab_name=main&is_search=0&list_name=follow&nt=1
  - https://www.douyin.com/user/MS4wLjABAAAAHuFui7x3Walw7nu61E_iQgXBU-23twsaX4FGWpb_bmo?from_tab_name=main&is_search=0&list_name=follow&nt=6
  - https://www.douyin.com/user/MS4wLjABAAAAMAXz3VO8HKNNCI-a5cu_qTpMcUVqUgEtflDFmNAhWYA?from_tab_name=main&is_search=0&list_name=follow&nt=5
  - https://www.douyin.com/user/MS4wLjABAAAAhyi_rpWe4KzEuLZonsXd5ppCowlJEAnkIdR3I4UoG3StFUaTul3-NQE1gpwtj39P?from_tab_name=main&is_search=0&list_name=follow&nt=1
  - https://www.douyin.com/user/MS4wLjABAAAAfeAVsklc4_BZ6mK4hGQV7ZXMX2-UrIxKzijhHp5CCp0?from_tab_name=main&is_search=0&list_name=follow&nt=6
  - https://www.douyin.com/user/MS4wLjABAAAAZ6_RACbyJWVhxeNIbKH58N7vbqRb6Z1AOuW2XQGrSUg?enter_from=discover&enter_method=follow_list&from_tab_name=main&is_search=0&list_name=follow&nt=1&tab_name=follow_lish
  - https://www.douyin.com/user/MS4wLjABAAAAE-MdOEUd6XRj5rgj4tT-VA-0DApIZNwuYZXckFQHhcQ?from_tab_name=main&is_search=0&list_name=follow&nt=2
  - https://www.douyin.com/user/MS4wLjABAAAAWmyy7bPzS5Z3qcHrgkwrqYq_-fvXE0WrYQMCVe91kaILdhv7hzuQSXsikuGxRzZt?from_tab_name=main&is_search=0&list_name=follow&nt=2
  - https://www.douyin.com/user/MS4wLjABAAAAM2oJ4uH5FwsEa7O1i3Hf-Zp13XCP_LuqVprl9hRtAk8Qp_r-Z8ozsRRdS7lymeRF?from_tab_name=main&is_search=0&list_name=follow&nt=3
# 直播链接示例
# 下载保存位置, 默认当前文件位置
# 必选
path: ./Download/

# 是否下载视频中的音乐(True/False), 默认为True
# 可选
music: False

# 是否下载视频的封面(True/False), 默认为True, 当下载视频时有效
# 可选
cover: False

# 是否下载作者的头像(True/False), 默认为True
# 可选
avatar: False

# 是否保存获取到的数据(True/False), 默认为True
# 可选
json: False


# 下载时间范围 (留空表示不限制时间)
# 格式: "YYYY-MM-DD" 例如: "2024-01-01"
start_time: ""
end_time: ""


# 文件夹结构设置
folderstyle: False # True -> 每个视频是一个单独的文件夹; False -> 所有视频共用一个文件夹
# True 的文件夹结构:
# user_xxx_xxx
#   - like/post/mix
#       - 2022-11-28 13.09.56_xxx
#         - 2022-11-28 13.09.56_xxx.mp4
#       - 2022-11-29 12.09.56_xxx
#         - 2022-11-29 12.09.56_xxx.mp4

# False 的文件夹结构:
# user_xxx_xxx
#   - like/post/mix
#       - 2022-11-28 13.09.56_xxx.mp4
#       - 2022-11-29 12.09.56_xxx.mp4

# link是个人主页时, 设置下载发布的作品(post)或喜欢的作品(like)或者用户所有合集(mix), 默认为post, 可以设置多种模式
# 可选模式: post, like, mix, music
# 可选
mode:
  - post
  # - like
  # - mix
  # - music

# 下载作品个数设置
# 可选
number:
  post: 0     # 主页下作品下载个数设置, 默认为0 全部下载
  like: 0     # 主页下喜欢下载个数设置, 默认为0 全部下载
  allmix: 0   # 主页下合集下载个数设置, 默认为0 全部下载
  mix: 0      # 单个合集下作品下载个数设置, 默认为0 全部下载
  music: 0    # 音乐(原声)下作品下载个数设置, 默认为0 全部下载

# 是否使用数据库存储下载记录
database: True # 如果不使用数据库, 增量更新将不可用



# 增量下载, 下载作品范围: 抖音最新作品到本地的最新作品之间的作品, 如果本地没有该链接的任何视频则全部下载
# 可配合 number 选项一起使用
# 情况1: number(假如设置5) 和 increase(假如抖音博主更新了3条作品,本地并未下载) 则会获取5条数据并下载
# 情况2: number(假如设置5) 和 increase(假如抖音博主更新了6条作品,本地并未下载) 则会获取6条数据并下载
# 情况3: number(假如设置5) 和 increase(假如本地并未下载该博主视频) 则会获取所有的视频
# 情况4: 当获取主页所有mix时(mode是mix模式)比较特殊, number(allmix) 控制下载多少个合集, increase(allmix) 对每个合集进行增量更新
# 可选
increase:
  post: False     # 是否开启主页作品增量下载(True/False), 默认为False
  like: False     # 是否开启主页喜欢增量下载(True/False), 默认为False
  allmix: False   # 是否开启主页合集增量下载(True/False), 默认为False
  mix: False      # 是否开启单个合集下作品增量下载(True/False), 默认为False
  music: False    # 是否开启音乐(原声)下作品增量下载(True/False), 默认为False

# 设置线程数, 默认5个线程
# 可选
thread: 5

# cookie 请登录网页抖音后F12查看
# cookies 和 cookie 二选一, 要使用这种形式, 请注释下面的cookie
# 目前只需要msToken、ttwid、odin_tt、passport_csrf_token、sid_guard
# 可以动态添加, 程序会根据填的键查找，并没有写死, 如果抖音需要更多的cookie自己加上就行了
cookies:
  # 请将下面的示例值替换为你的真实cookie值
  # 获取方式: 登录网页抖音后按F12打开开发者工具，在Network标签页中找到请求头中的cookie
#  msToken: YOUR_MS_TOKEN_HERE
  ttwid: 1%7Cbtyyc0x94GFrMmoPJ4CSihfBKcCUrQyR0XP0IKPCmxs%7C1752374504%7Cedd0c085556ed4484f736abd915dd16b7428c9e6b87ac55eb88455f0f2aa4472
  odin_tt: aa01a110a69c1c6a7339d5e71815cd400e80310847231d69251794ebbfef98ea3880db79e44fa23751a9013d406f65985e74273d31fb34e9a451d26c4a2d02033c1e6c8bd31ce0328d1fa2a01b96db7b
  passport_csrf_token: 58dcb94a111f0bac9d2a35cf9a9c69a4
  sid_guard: 5cd7b01f23e5abb3dced5dbd2051201a%7C1750847672%7C5184000%7CSun%2C+24-Aug-2025+10%3A34%3A32+GMT
  seessionid: 5cd7b01f23e5abb3dced5dbd2051201a
  uid_tt: 6649a4648199a9e12765cbfd2a91602f
  ms_token: YOUR_MS_TOKEN_HERE
#
#enter_pc_once=1;
#  UIFID_TEMP=e71d819f1cb72e7166823ce125547a3e5a83b631a52f7c0b3c34cd9714dd602db692f7a8460ec9b2042cf04cc3210bde90f857514e19a682a2975c4cc67aabe7cef52acba9805987195222715564e0c1;
#  hevc_supported=true;
#  volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Afalse%2C%22volume%22%3A0.6%7D;
#  passport_csrf_token=58dcb94a111f0bac9d2a35cf9a9c69a4;
#  passport_csrf_token_default=58dcb94a111f0bac9d2a35cf9a9c69a4;
#  __security_mc_1_s_sdk_crypt_sdk=f21144b1-45fe-be65;
#  bd_ticket_guard_client_web_domain=2;
#  UIFID=e71d819f1cb72e7166823ce125547a3e5a83b631a52f7c0b3c34cd9714dd602d7d750ae6ea97d549c524baf2205a2c6a01b1850269c1451ff5ad4b027afda44b9fb009cd427c93130c65dddab0fd4008acd4175b7dc082d3a63d6b90e25aaabc343291bf5007723256ea0c87ee29202c0496c3ee277c33dbca52263c84849f837b5de083f15dd33fbe0e93c1655f0d845b0f665d70c6cbf2ca45b7b015b5da59;
#  passport_mfa_token=CjdYqh6tg2z1cTSVGeGMGUo53nhet%2BfNkv90BpuuvkpaoB%2Fxe2fDw5ETf0SAPlfyYYjhRfE6DjeIGkoKPAAAAAAAAAAAAABPKKvLaxJrHK%2FSus65uJ14ixgZG4et%2F3IJ%2BnxT4me7J97JhGQfLBVfnxlZBg5tzlNNexCMhfUNGPax0WwgAiIBA%2BclnT0%3D;
#  d_ticket=358d365d31a5bd2c33ffeee62500f8cb4a426;
#  passport_assist_user=CkGMZgz5vTX46M2vOTRXq_HYY3ofWAk81CbMDk3NZkbMyMZggjeboxPsSaDFyuQLNPIbF4ZXvh2fH1XYCdRqML2IZxpKCjwAAAAAAAAAAAAATygSUm19z7U2go5_H9egEYnVhB6bIVMmDR9YZJwpCBY-IUT6vMXGEL5g6EOG5rcU5jQQxIb1DRiJr9ZUIAEiAQMSGzDP;
#  n_mh=9tKskabWQ1gvf_MUNx7Q269BNA9ToOOGz4mLIqtBlHI;
#  sid_guard=5cd7b01f23e5abb3dced5dbd2051201a%7C1750847672%7C5184000%7CSun%2C+24-Aug-2025+10%3A34%3A32+GMT;
#  uid_tt=6649a4648199a9e12765cbfd2a91602f;
#  uid_tt_ss=6649a4648199a9e12765cbfd2a91602f;
#  sid_tt=5cd7b01f23e5abb3dced5dbd2051201a;
#  sessionid=5cd7b01f23e5abb3dced5dbd2051201a;
#  sessionid_ss=5cd7b01f23e5abb3dced5dbd2051201a;
#  is_staff_user=false;
#  sid_ucp_v1=1.0.0-KGQwZjgwNjY2NGM2YmZiM2JkOTVmMDZjNDM1M2RmYzY3NjY2YWNkZWIKIQjNxNC1hPTCBxC4oe_CBhjvMSAMMJ7YkegFOAdA9AdIBBoCaGwiIDVjZDdiMDFmMjNlNWFiYjNkY2VkNWRiZDIwNTEyMDFh;
#  ssid_ucp_v1=1.0.0-KGQwZjgwNjY2NGM2YmZiM2JkOTVmMDZjNDM1M2RmYzY3NjY2YWNkZWIKIQjNxNC1hPTCBxC4oe_CBhjvMSAMMJ7YkegFOAdA9AdIBBoCaGwiIDVjZDdiMDFmMjNlNWFiYjNkY2VkNWRiZDIwNTEyMDFh;
#  login_time=1750847672615;
#  _bd_ticket_crypt_cookie=48ed4e1384077e2eeb33dab05f370ec2;
#  __security_mc_1_s_sdk_sign_data_key_web_protect=03ba325e-4067-a735;
#  __security_mc_1_s_sdk_cert_key=40a39ccf-4d27-8685;
#  __security_server_data_status=1;
#  live_use_vvc=%22false%22;
#  SelfTabRedDotControl=%5B%7B%22id%22%3A%227444479931649624079%22%2C%22u%22%3A30%2C%22c%22%3A30%7D%5D;
#  my_rd=2;
#  session_tlb_tag=sttt%7C11%7CXNewHyPlq7Pc7V29IFEgGv_________hkS1S5hces1tjiYTqSwVpo_W6snGMSyf8mwp0fsZnPQc%3D;
#  is_dash_user=1; publish_badge_show_info=%220%2C0%2C0%2C1752374297185%22;
#  gulu_source_res=eyJwX2luIjoiYTlmMjU3NzAxMWQ2OTIyYjc5NWQ5Zjk3NjY1OWVkOTNkMGQ2NjBjMWZhMmNkYzdjMGI4NmI5YTU2YjlhYmU1OCJ9;
#  strategyABtestKey=%221752374313.734%22;
#  stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1920%2C%5C%22screen_height%5C%22%3A1080%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A32%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A10%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A50%7D%22;
#  home_can_add_dy_2_desktop=%221%22;
#  bd_ticket_guard_client_data=eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCUDlyV3FRVHk2UWxNNW1YcVNRYVdIUEZXeGJYZWNnTi9HUEVpbkdYa2FYNDJ0WVRTdlpZeW1HNUxQcUlLSGpWNmRvQVE1OFQ3WFJnYUpBYkhHYzU4SjQ9IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoyfQ%3D%3D;
#  odin_tt=aa01a110a69c1c6a7339d5e71815cd400e80310847231d69251794ebbfef98ea3880db79e44fa23751a9013d406f65985e74273d31fb34e9a451d26c4a2d02033c1e6c8bd31ce0328d1fa2a01b96db7b;
#  ttwid=1%7Cbtyyc0x94GFrMmoPJ4CSihfBKcCUrQyR0XP0IKPCmxs%7C1752374504%7Cedd0c085556ed4484f736abd915dd16b7428c9e6b87ac55eb88455f0f2aa4472;
#  biz_trace_id=077a63a5;
#  sdk_source_info=7e276470716a68645a606960273f276364697660272927676c715a6d6069756077273f276364697660272927666d776a68605a607d71606b766c6a6b5a7666776c7571273f275e58272927666a6b766a69605a696c6061273f27636469766027292762696a6764695a7364776c6467696076273f275e582729277672715a646971273f2763646976602729277f6b5a666475273f2763646976602729276d6a6e5a6b6a716c273f2763646976602729276c6b6f5a7f6367273f27636469766027292771273f273c3537323d3231323637303234272927676c715a75776a716a666a69273f2763646976602778;
#  bit_env=6gkiJdohFfHmeGYG_ndhFaiDc8iBLFNAeLF8TkVn3pdKdyaiX1DNP9y7fgLwsCBjGlqLhEydStYrdynNjArAnaRSVr0iX1mQBVgG_mcroDmWh6FUdlOCjHcK-9JFKEK7iddJFzHRujmvcmhUPsPZxSKDiqvuX5PXMP_UblHUt3pjXQWOV9HyDW8oZO8DquHVRysnzMCTZvbqB-Rnql0mIL3NMqX2vsUQyRYls8Akh4yBbdWDDijOKoVq4CfwtQRr-i85MRG8Ju-FpEWiwIxcJDwn_wdQBowADglBsb68ehdsFba0P6SwrjghWngQSNga_PB34OFR1Qv14pdCXH9yd3gGuVaRdt8xC_840dt16cdUePEjdYZWik8tat9nkbCbvpNoGgBUBPORdMd-2rJhfCK7qCEuzXSi79abm6PxDDByNKuW3HeuocaluqaeYEgsHtjM4mXrSxfyThhAS7ZeDvPpl3mM5PCNYIUSfeNsWyZKV8ybRrmmaVAbGXZbR7tN;
#  passport_auth_mix_state=ug2m1rx7ob6by8lqphnmtrp862pe8w6z;
#  IsDouyinActive=true
# cookie 请登录网页抖音后F12查看
# cookies 和 cookie 二选一, 要使用这种形式, 请注释上面的cookies及包含的所有键值对
# 设置了这个后上面的cookies选项自动失效, 这个优先级更高
# 格式: "name1=value1; name2=value2;" 注意要加分号
# 分号中的内容包括不限于以下键值对, 如果抖音需要更多的cookie自己加上就行了
# cookie: "msToken=YOUR_MS_TOKEN; ttwid=YOUR_TTWID; odin_tt=YOUR_ODIN_TT; passport_csrf_token=YOUR_CSRF_TOKEN; sid_guard=YOUR_SID_GUARD; sessionid=YOUR_SESSION_ID; uid_tt=YOUR_UID_TT;"

